manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: Tee-nahan
      url-base: https://github.com/Tee-nahan/zmk-dongle-display
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    - name: zmk-dongle-display
      remote: Tee-nahan
      revision: main
  self:
    path: config